#!/usr/bin/env python3
"""Build public/index.json and CATALOG.md from plugins/*.json.

The index inlines the full manifests (they're small), so the app installs a
plugin by persisting the manifest locally — no second fetch needed. CATALOG.md
is the human-browsable version of the same data — never edit it by hand.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PLUGINS = ROOT / "plugins"
OUT = ROOT / "public" / "index.json"
CATALOG = ROOT / "CATALOG.md"

KIND_LABEL = {"ai": "AI prompt", "shell": "Shell", "url": "URL"}


def md_escape(text):
    return str(text).replace("|", "\\|").replace("\n", " ")


def write_catalog(packs):
    lines = [
        "# Plugin Catalog",
        "",
        "<!-- AUTO-GENERATED by scripts/build_index.py — do not edit by hand. -->",
        "",
        f"{len(packs)} plugin pack(s). Install from **Slashbar → Settings → Plugins**.",
        "",
    ]
    for pack in packs:
        kinds = sorted({c.get("kind", "?") for c in pack.get("commands", [])})
        shell_note = " ⚠️ *runs shell commands*" if "shell" in kinds else ""
        title = f"## {pack['name']} `v{pack['version']}`"
        lines += [
            title,
            "",
            f"{pack['description']} — by **{pack['author']}**"
            f" · kinds: {', '.join(KIND_LABEL.get(k, k) for k in kinds)}{shell_note}",
            "",
        ]
        if pack.get("homepage"):
            lines += [f"[Homepage]({pack['homepage']}) · `{pack['id']}`", ""]
        else:
            lines += [f"`{pack['id']}`", ""]
        lines += ["| Command | Kind | Description |", "|---|---|---|"]
        for cmd in pack.get("commands", []):
            desc = cmd.get("description") or ""
            lines.append(
                f"| {md_escape(cmd['name'])} | {KIND_LABEL.get(cmd.get('kind'), '?')} "
                f"| {md_escape(desc)} |")
        lines.append("")
    CATALOG.write_text("\n".join(lines), encoding="utf-8")


def main():
    packs = []
    for path in sorted(PLUGINS.glob("*.json")):
        packs.append(json.loads(path.read_text(encoding="utf-8")))
    OUT.parent.mkdir(parents=True, exist_ok=True)
    index = {"schema": 1, "plugins": packs}
    OUT.write_text(json.dumps(index, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    write_catalog(packs)
    print(f"wrote {OUT.relative_to(ROOT)} and {CATALOG.name} with {len(packs)} plugin(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
